vda/quiz/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
from quiz.views import HomeView, QuizView, ProgressView

app_name = 'quiz'

########## URls to the three HTML templates and what Views they use ##########

urlpatterns = [
    #When use is directed to a page, the page id is passed to and from the view and the template through the URL.
    path('quiz/<int:page_id>/', QuizView.as_view(), name='quiz'),
    path('quiz/', QuizView.as_view(), name='quiz_post'),
    path('', HomeView.as_view(), name='index'),
    path('progress/', ProgressView.as_view(), name='progress'),
]

vda/vda/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

vda/quiz/models.py
from django.db import models
######### Entities of the database being used #########
######### Must makemigrations and migrate when and if any changes are made #########
class Page(models.Model):
    page_id = models.AutoField(primary_key=True)
    prev_page = models.PositiveSmallIntegerField(default=0)
    next_page = models.PositiveSmallIntegerField(default=0)
    text = models.TextField(max_length=1000)
    step = models.PositiveSmallIntegerField(default=0)
    page_score = models.PositiveSmallIntegerField(default=0)

class Image(models.Model):
    image_id = models.AutoField(primary_key=True)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    imgname = models.CharField(max_length=100)

class Quote(models.Model):
    quote_id = models.AutoField(primary_key=True)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

class Title(models.Model):
    title_id = models.AutoField(primary_key=True)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

class Button(models.Model):
    button_id = models.AutoField(primary_key=True)
    next_page = models.ForeignKey(Page, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

class ButtonAction(models.Model):
    button_action_id = models.AutoField(primary_key=True)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    button = models.ForeignKey(Button, on_delete=models.CASCADE)

class Question(models.Model):
    question_id = models.AutoField(primary_key=True)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    type = models.CharField(max_length=50)
    worth_points = models.BooleanField(default=False)

class MultichoiceAnswer(models.Model):
    multichoice_answer_id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    next_page = models.ForeignKey(Page, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)

class CheckboxAnswer(models.Model):
    checkbox_answer_id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    correct = models.BooleanField(default=False)

class Score(models.Model):
    username = models.CharField(max_length=50, primary_key=True)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    current_score = models.PositiveSmallIntegerField(default=0)
    current_step = models.PositiveSmallIntegerField(default=0)
    nextqp = models.PositiveSmallIntegerField(default=0)

vda/quiz/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import (authenticate, login, get_user_model, logout,)
from django.views.generic import View
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
import re
from bs4 import BeautifulSoup
import json
import datetime
from django.contrib import messages
import requests
import random


from .models import *

######### Homepage #########
class HomeView(View):
    def get(self, request):
        return render(request,'quiz/index.html')

    def post(self, request):
        current_username = request.POST.get('username')
        ## Checks if username input is empty and redirects to the index
        ## If it is empty, "is_invalid" is passed to the template to be included in the username input tag,
        ## which will outline the input area with red to alert the user of empty input
        if not current_username:
            invalid = "is-invalid"
            return render(request,'quiz/index.html', {'invalid': invalid})
        ## If username input is not empty and if the user exists, the user is then logged in
        else:
            ## Creates a Score object for the user with the default starting information and the username provided if they do not already exist
            if not Score.objects.filter(username=current_username):
                starting_page = Page.objects.get(page_id=1)
                starting_score = 0
                starting_step = 1
                new_user_score = Score.objects.create(username=current_username, current_step=starting_step, current_score=starting_score, page=starting_page, nextqp=0)
                new_user_score.save()
            if User.objects.filter(username=current_username):
                user = User.objects.get(username=current_username)
                login(request, user)
            ## If the user does not exist, creates new User object with the information provided and logs in the new user
            else:
                new_user = User.objects.create_user(current_username, current_username + '@email.com', 'password')
                login(request, new_user)

            ## Once verification and or user creation is complete, the user is logged in and redirected to the progress page
            return HttpResponseRedirect(reverse('quiz:progress'))

######### Quiz #########
class QuizView(View):
    def get(self, request, page_id):
        ## Initializing empty string variables that require conditions to be met in order to be assigned with appropriate values
        ## This is done so that we can pass on empty variables rather than have multiple returns for different conditions, to reduce code duplication
        question = answers = button = quote = nextstate = prevstate = question_type = ""

        page = Page.objects.get(page_id=page_id)
        ## Retrieving any existing quote(s) for the current page
        if Quote.objects.filter(page_id=page_id):
            quote = Quote.objects.get(page=page)
        ## Retrieves any existing question, and its answers based on question type for the current page
        if Question.objects.filter(page=page):
            question = Question.objects.get(page=page)
            question_type = question.type
            if question.type == "multichoice":
                answers = MultichoiceAnswer.objects.filter(question=question.question_id).order_by('?')
            else:
                answers = CheckboxAnswer.objects.filter(question=question.question_id)
        ## If no questions exist for the current page, a button action will, which is then used to retrieve the button
        if ButtonAction.objects.filter(page=page):
            button = Button.objects.get(button_id=(ButtonAction.objects.get(page=page)).button.button_id)


        ## Setting the next and previous page id values
        next = page.next_page
        prev = page.prev_page

        user = Score.objects.get(username=request.user.username)
        ## Computing if previous or next button should be clickable
        ## Next button is disabled if the user is on a page that is higher than their farther reached page stored in their Score instance
        if user.page.page_id < page.next_page:
            nextstate = "disabled"
        ## Previous button is disabled if they're on the first page of the quiz
        if page_id == 1:
            prevstate = "disabled"

        ## Any existing title and image for the current page is retrieved and passed on to the quiz template
        title = Title.objects.filter(page_id=page_id)
        image = Image.objects.filter(page_id=page_id)
        return render(request, 'quiz/quiz.html',
                      {'page': page, 'question': question, "question_type": question_type,"answers": answers, 'name': user,
                       'title': title, 'image':image, 'button': button, 'quote': quote, 'next': next, 'prev': prev, 'nextstate': nextstate, 'prevstate': prevstate})

    def post(self, request):
        ## Checks which submit button has been clicked and runs the designated code
        if 'next_page' in request.POST:
            current_user = Score.objects.get(username=request.user.username)
            next_page = int(request.POST.get('next_page'))
            ## Only updates user's score if they have not already attempted the question
            ## Checks their last answered question against the current page
            if current_user.nextqp < int(request.POST.get('current')):
                ## Updates their last answered to the latest answered question page id
                current_user.nextqp = current_user.page.page_id
                current_user.page = Page.objects.get(page_id=next_page)
                current_user.current_step = current_user.page.step
                ## Score computation for checbox answers
                if request.POST.getlist('answers[]'):
                    ## Sets total for 5 checkboxes where 2 answers will be incorrect
                    correct = len(request.POST.getlist('incorrect[]'))
                    total = len(request.POST.getlist('total[]'))
                    ## For every answer checked if true add 1 to correct and if false minus 1 off correct
                    for a in request.POST.getlist('answers[]'):
                        if a == "True":
                            correct += 1
                        else:
                            correct -= 1
                    ## Add to users score the page total divided by total and then multiplied by the amount
                    ## user got correct
                    current_user.current_score += ((current_user.page.page_score / total) * correct)
                ## If question was multichoice just add page's score
                else:
                    current_user.current_score += Page.objects.get(page_id=next_page).page_score
                ## Updates the current step for the user based on the what step the current page is assigned to
                current_user.save()
            ## Sets the page_id to appropriate next_page id retrieved from the template
            page_id = next_page
        elif 'previous' in request.POST:
            ## Sets the page_id to the previous page_id
            page_id = int(request.POST.get('previous'))
        else:
            ## Sets the page_id to the next page_id
            page_id = int(request.POST.get('next'))
        return HttpResponseRedirect(reverse('quiz:quiz', kwargs={'page_id':page_id}))

######### Progress #########
class ProgressView(View):
    def get(self, request):
        user = Score.objects.get(username=request.user.username)
        page = Page.objects.get(page_id=user.page.page_id)
        ## Creates a temporary dictionary with 0 values to represent each of the five steps
        progress = {1 : 0, 2 : 0, 3 : 0, 4 : 0, 5 : 0}
        total_scores = 0
        overall_score = 0
        ## Using the farthest reached page by the user, retrieves the farthest step
        for i in range(1, page.step+1):
            ## Filters all the pages for each of the steps and retrieves the count of pages
            pages = Page.objects.filter(step=i).order_by("pk")
            page_count = len(pages)

            ## Checks every page in the step and saves the users current page
            for p in range(page_count):
                if pages[p].page_id == user.page.page_id:
                    current_page = p
            ## Checks if the current step being calculated is less than the farthest reached step
            ## If so, automatically assigns 100 percent completion for that step
            ## Does the same if the users current page is the same as the total count pages in the step, meaning they have reached the end of that step
            if i < page.step or current_page == page_count:
                progress[i] = 100
                ## Score calculation in this instance is simple as the user has completed the step:
                ## Add up all the points available in all the pages in the current step, use that in the final calculation below to calculate overall score
                for p in pages:
                    total_scores += p.page_score
            ## If the user is currently on a step that they have not completed,
            ## Uses page count of the step and the index of the current page in relation to the page count of the step to calculate the percentage completed
            else:
                progress[i] = int((100 / page_count) * current_page)
                ## Calculating score for incomplete step:

vda/quiz/templates/quiz/index.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />

{% block content %}

<div style="border-radius: 5px 5px 5px 5px;" class="cont">
    <h2>Welcome to the Viewpoint Diversity App!</h2><br>
    <div class="justify">
    <p>A free interactive platform designed to depolarize communities and foster mutual understanding across differences</p>
    <p>Viewpoint Diversity is a psychology-based educational platform designed to bring people together in campuses, companies, organizations, and communities.
        Viewpoint Diversity helps people foster intellectual humility and mutual understanding, while equipping them with the essential cognitive skills to engage constructively across differences.</p>
    </div>
    <form action="{% url 'quiz:index' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" placeholder="Username" class="form-control {{invalid}}" name="username" id="username">
        </div>
            <button class="btn btn-outline-secondary" type="submit" >Begin Quiz</button>
    </form>
</div>
{% endblock %}

vda/quiz/templates/quiz/progress.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />

{% block content %}
<nav class="navbar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link active" href="/progress">PROGRESS</a>
    </li>
  </ul>
    <a class="nav-link active logout" href="/">LOGOUT</a>
</nav>
<div class="cont">
    <h2>Welcome {{username}}</h2>
    <div class="justify">
        {% for key, value in progress.items %}
            <p style="font-size: 120%;">Step {{key}}:</p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: {{value}}%; padding-left: {{padding}};" aria-valuenow="{{value}}" aria-valuemin="0" aria-valuemax="100">{{value}}%</div>
            </div>
        {% endfor %}
        <br><h4 class="underline">Overall score: {{user_score}}% of quiz questions right</h4>
        <form action="{% url 'quiz:progress' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <button class="btn btn-outline-secondary progr" type="submit" >Continue</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

vda/quiz/templates/quiz/quiz.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />

{% block content %}
<nav class="navbar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link active" href="/progress">PROGRESS</a>
    </li>
  </ul>
    <a class="nav-link active logout" href="/">LOGOUT</a>
</nav>
<div class="cont">
    <form action="{% url 'quiz:quiz_post' %}" method="post">
        {% csrf_token %}
        <div id="wrapper">
            <h3 class="inline">Score: {{ name.current_score }}</h3>
            <div class="sec_nav">
                <button class="btn btn-outline-secondary prev" type="submit" {{prevstate}} name='previous' value={{prev}}>Previous</button>
                <button class="btn btn-outline-secondary next" type="submit" {{nextstate}} name='next' value={{next}}>Next</button>
            </div>
        </div>
        {% for t in title %}
            <h2>{{t.text}}</h2>
        {% endfor %}
        <br>
        <div class="justify">
            {{page.text}}
        </div>
        {% for i in image %}
            <img class="img" src="/static/quiz/images/{{i.imgname}}" alt="{{i.imgname}}">
        {% endfor %}

        {% if quote != "" %}
        <br><i>{{ quote.text }}</i>
        {% endif %}

        {% if question != "" %}
            {% if question.worth_points %}
                <h4 class="question"><span class="fa fa-star" aria-hidden="true"></span>  {{ question.text}}</h4>
            {% else %}
                <h4 class="question">{{ question.text}}</h4>
            {% endif %}
        {% endif %}
            {% if question_type == "multichoice" %}
                {% for a in answers %}
                    <button class="btn btn-outline-secondary" type="submit" name='next_page' value={{a.next_page.page_id}}>{{ a.text }}</button><br>
                {% endfor %}
            {% else %}
                {% if question_type == "checkbox" %}
                    {% for a in answers %}
                        <label class="container">{{a.text}}
                            <input type="checkbox" name="answers[]" value="{{a.correct}}">
                            <span class="checkmark"></span>
                            <input type="hidden" name="total[]" value="answer">
                            {% if not a.correct %}
                                <input type="hidden" name="incorrect[]" value="answer">
                            {% endif %}
                        </label>
                    {% endfor %}
                {% endif %}
                <button class="btn btn-outline-secondary" type="submit" name='next_page' value={{button.next_page.page_id}}>{{ button.text }}</button>
            {% endif %}
        <input type="hidden" name="current" value="{{page.page_id}}">
    </form>
</div>
{% endblock %}